site_name: Knoblands

theme:
    name: material
    favicon: img/favicon.ico
    logo: img/favicon.ico
    features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: knoblands
      accent: knoblands
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: knoblands
      accent: knoblands
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    extra_css:
    - stylesheets/extra.css

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: DezziDez
      repo: Knoblands
      normalize_issue_symbols: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.fancylists
  - nl2br
  - admonition
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - full_yaml_metadata
  - toc:
        permalink: true
        baselevel: 2
        toc_depth: 3
        separator: "-"